# Generated by Django 2.1.1 on 2019-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='null', max_length=511),
            preserve_default=False,
        ),
    ]
