# Generated by Django 2.1.1 on 2019-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_search', '0002_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='videoUrl',
        ),
        migrations.AddField(
            model_name='video',
            name='publishedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnailUrl',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
    ]
