# Generated by Django 2.1.1 on 2019-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_search', '0003_auto_20190401_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='channelId',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='channelTitle',
            new_name='channel_title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnailUrl',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='videoId',
            new_name='video_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='videoUrl',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='publishedAt',
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(default='2019-04-05 14:28:31.619429'),
            preserve_default=False,
        ),
    ]
